### ISSUE TITLE
Won't install via pip (python 2.7)

### ISSUE THREAD

**Issue by andredaa** [chris48s/geojson-rewind#1]
Collecting geojson-rewind
  Using cached https://files.pythonhosted.org/packages/ce/f2/7adbb1f4e0568749219108efde5180a88788ca59d8d71315a8449120f614/geojson-rewind-0.1.1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4N13RH/geojson-rewind/setup.py", line 18, in <module>
        long_description=_get_description(),
      File "/tmp/pip-install-4N13RH/geojson-rewind/setup.py", line 7, in _get_description
        with open(path, encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-4N13RH/geojson-rewind/

**Comment by chris48s** [comment]
Hello.
This library is python 3 only as noted in the declared platform support:

https://github.com/chris48s/geojson-rewind/blob/master/setup.py#L30-L34

![Python Support](https://img.shields.io/pypi/pyversions/geojson-rewind.svg)

I don't plan to make any changes for compatibility with python 2 as python 2.7 is approaching end of life.
Cheers

**Comment by andredaa** [comment]
Hello thanks for your reply.
I understand that. Unfortunately we are bound to python2 due to other
dependencies. But there will be another solution :)
Best regards
Andre
