### ISSUE TITLE
Consider merging project with Python GeoJSON?

### ISSUE THREAD

**Issue by rayrrr** [chris48s/geojson-rewind#24]
Hi @chris48s, thanks for making this useful project.

I'm writing to you today as part of a 1200-member-strong community of Python open source contributors called [Jazzband](https://jazzband.co), and am the current project lead/maintainer for the Jazzband-managed https://github.com/jazzband/geojson, where we have a [long-running feature request](https://github.com/jazzband/geojson/issues/37) for rewinding functionality within that core GeoJSON Python package.

Because of the winding constraint not being included in the original 2008 spec, and backwards compatibility being recommended in the final spec, I believe the ideal behavior would be for the GeoJSON package to accept the geometries in either winding order, but always output them in the correct winding order.

The exact quote from the spec, section 3.1.6:

> Note: the [[GJ2008](https://www.rfc-editor.org/rfc/rfc7946#ref-GJ2008)] specification did not discuss linear ring winding order.  For backwards compatibility, parsers SHOULD NOT reject Polygons that do not follow the right-hand rule.

Would you be interested in merging this work into that core package to help build out that functionality, and joining Jazzband so you can continue to easily contribute? We would welcome that. Otherwise we may end up developing some duplicative functionality in the core library.

Let us know!

**Comment by chris48s** [comment]
Hi. I'm aware of both JazzBand and jazzband/geojson.

If you want to use this code in jazzband/geojson, you can pull it in as a dependency. I do keep the package maintained.
It is probably not necessary, but if you prefer to hard-fork/vendor the code for whatever reason, feel free - its MIT licenced.

I'm not really interested in getting involved with the maintenance of jazzband/geojson at this time - its a more complicated project with different aims to this one - but I wish you luck with it. 

Cheers

**Comment by rayrrr** [comment]
Thanks for letting us know so quickly. Cheers
