### ISSUE TITLE
Incorrect winding chosen

### ISSUE THREAD

**Issue by mbway** [chris48s/geojson-rewind#8]
I noticed that the incorrect winding was being chosen for some polygons I was passing to this library and narrowed it down to strange values being produced by ringArea. It looks like ringArea expects geo-coordinates as longitude, latitude. Is that correct? If so then this should be documented somewhere. If not, then `ringArea` should be replaced to an algorithm which can calculate the signed area of any polygon.

```python
from geojson_rewind.rewind import ringArea

ring = [(0.0, 0.0), (10.0, 0.0), (10.0, 10.0), (0.0, 10.0), (0.0, 0.0)]

print(ringArea(ring))  # -1232921098571.2913
print(ringArea([(x + 85, y + 85) for x, y in ring]))  # 0.0
print(ringArea([(x + 86, y + 86) for x, y in ring]))  # 21599633242.964127

from shapely.geometry import LinearRing
from shapely.algorithms.cga import signed_area

print(signed_area(LinearRing(ring)))  # 100
print(signed_area(LinearRing([(x + 85, y + 85) for x, y in ring])))  # 100
print(signed_area(LinearRing([(x + 86, y + 86) for x, y in ring])))  # 100
```

The implementation of `shapely.algorithms.cga.signed_area` is an example of how this function could be implemented

**Comment by chris48s** [comment]
Yes. GeoJSON uses (lon, lat) order. This is documented in the spec https://tools.ietf.org/html/rfc7946#section-3.1.1

> A position is an array of numbers.  There MUST be two or more
> elements.  The first two elements are longitude and latitude, or
> easting and northing, precisely in that order and using decimal
> numbers.

That ordering is assumed and passing an input with co-ordinates the other way around would result in unexpected behaviour. GeoJSON using the (lat, lon) ordering will result in GeoJSON that probably doesn't work with most other tools too :upside_down_face: 

I suspect I'm more likely to just document that and keep the implementation close to the upstream lib but I'll have a think about it. It would probably also make sense to throw or warn if a legacy non-standard `crs` key is declared https://tools.ietf.org/html/rfc7946#section-4 too for similar reasons.

**Comment by mbway** [comment]
ok. I didn't realise that geojson _requires_ WGS84, especially since I often see CRS definitions in the geojson files I'm working with which would be pointless if there was no choice. But if that's a legacy feature then it makes sense.

I thought that geojson was agnostic to the coordinate system since libraries like shapely have identical data structures and are often used for non-geographic purposes. I will probably roll my own implementation which handles data in the way that I need.
